enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[bilibili]
apkmirror-dlurl = "https://www.apkmirror.com/apk/bilibili/bilibili/"
patches-source = "BiliRoamingX/BiliRoamingX"
integrations-source = "BiliRoamingX/BiliRoamingX"
rv-brand = "BiliRoamingX ReVanced"
arch = "arm64-v8a"
build-mode = "both"
exclusive-patches = true
